<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ExceptionUtilsTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">threadly$All_in_threadly_test.exec</a> &gt; <a href="index.source.html" class="el_package">org.threadly.util</a> &gt; <span class="el_source">ExceptionUtilsTest.java</span></div><h1>ExceptionUtilsTest.java</h1><pre class="source lang-java linenums">package org.threadly.util;

import static org.junit.Assert.*;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.Collections;
import java.util.StringTokenizer;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.threadly.ThreadlyTester;
import org.threadly.concurrent.TestRuntimeFailureRunnable;
import org.threadly.test.concurrent.TestRunnable;
import org.threadly.util.ExceptionUtils.TransformedException;
import org.threadly.util.ExceptionUtils.TransformedSuppressedStackException;

@SuppressWarnings(&quot;javadoc&quot;)
<span class="fc" id="L21">public class ExceptionUtilsTest extends ThreadlyTester {</span>
  @Before
  @After
  public void cleanup() {
<span class="fc" id="L25">    ExceptionUtils.setDefaultExceptionHandler(null);</span>
<span class="fc" id="L26">    ExceptionUtils.setInheritableExceptionHandler(null);</span>
<span class="fc" id="L27">    ExceptionUtils.setThreadExceptionHandler(null);</span>
<span class="fc" id="L28">    Thread.setDefaultUncaughtExceptionHandler(null);</span>
<span class="fc" id="L29">    Thread.currentThread().setUncaughtExceptionHandler(null);</span>
<span class="fc" id="L30">  }</span>
  
  @Test
  @SuppressWarnings(&quot;deprecation&quot;)
  public void runRunnableTest() {
<span class="fc" id="L35">    TestRunnable tr = new TestRunnable();</span>
<span class="fc" id="L36">    ExceptionUtils.runRunnable(tr);</span>
    
<span class="fc" id="L38">    assertTrue(tr.ranOnce());</span>
<span class="fc" id="L39">  }</span>
  
  @Test
  @SuppressWarnings(&quot;deprecation&quot;)
  public void runRunnableThrownTest() {
<span class="fc" id="L44">    TestExceptionHandler exceptionHandler = new TestExceptionHandler();</span>
<span class="fc" id="L45">    ExceptionUtils.setThreadExceptionHandler(exceptionHandler);</span>
<span class="fc" id="L46">    RuntimeException failure = new SuppressedStackRuntimeException();</span>
<span class="fc" id="L47">    TestRuntimeFailureRunnable runnable = new TestRuntimeFailureRunnable(failure);</span>
    
<span class="fc" id="L49">    ExceptionUtils.runRunnable(runnable);</span>
    
<span class="pc bpc" id="L51" title="1 of 2 branches missed.">    assertTrue(exceptionHandler.getLastThrowable() == failure);</span>
<span class="fc" id="L52">  }</span>
  
  @Test
  public void getThreadLocalExceptionHandlerTest() {
<span class="fc" id="L56">    ExceptionUtils.setDefaultExceptionHandler(new TestExceptionHandler());</span>
<span class="fc" id="L57">    ExceptionUtils.setInheritableExceptionHandler(new TestExceptionHandler());</span>
<span class="fc" id="L58">    assertNull(ExceptionUtils.getThreadLocalExceptionHandler());</span>
    
<span class="fc" id="L60">    TestExceptionHandler exceptionHandler = new TestExceptionHandler();</span>
<span class="fc" id="L61">    ExceptionUtils.setThreadExceptionHandler(exceptionHandler);</span>
    
<span class="pc bpc" id="L63" title="1 of 2 branches missed.">    assertTrue(exceptionHandler == ExceptionUtils.getThreadLocalExceptionHandler());</span>
<span class="fc" id="L64">  }</span>
  
  @Test
  public void getThreadExceptionHandlerTest() {
<span class="fc" id="L68">    TestExceptionHandler defaultExceptionHandler = new TestExceptionHandler();</span>
<span class="fc" id="L69">    TestExceptionHandler inheritableExceptionHandler = new TestExceptionHandler();</span>
<span class="fc" id="L70">    TestExceptionHandler threadExceptionHandler = new TestExceptionHandler();</span>
    
<span class="fc" id="L72">    assertNull(ExceptionUtils.getExceptionHandler());</span>
    
    
<span class="fc" id="L75">    ExceptionUtils.setDefaultExceptionHandler(defaultExceptionHandler);</span>
<span class="pc bpc" id="L76" title="1 of 2 branches missed.">    assertTrue(defaultExceptionHandler == ExceptionUtils.getExceptionHandler());</span>
    
<span class="fc" id="L78">    ExceptionUtils.setInheritableExceptionHandler(inheritableExceptionHandler);</span>
<span class="pc bpc" id="L79" title="1 of 2 branches missed.">    assertTrue(inheritableExceptionHandler == ExceptionUtils.getExceptionHandler());</span>
    
<span class="fc" id="L81">    ExceptionUtils.setThreadExceptionHandler(threadExceptionHandler);</span>
<span class="pc bpc" id="L82" title="1 of 2 branches missed.">    assertTrue(threadExceptionHandler == ExceptionUtils.getExceptionHandler());</span>
<span class="fc" id="L83">  }</span>
  
  @Test
  @SuppressWarnings(&quot;resource&quot;)
  public void handleExceptionWithoutUncaughtExceptionHandler() {
    // make sure no uncaughtExceptionHandler is set
<span class="fc" id="L89">    Thread.setDefaultUncaughtExceptionHandler(null);</span>
<span class="fc" id="L90">    Thread.currentThread().setUncaughtExceptionHandler(null);</span>
    
<span class="fc" id="L92">    PrintStream originalSystemErr = System.err;</span>
    try {
      // set it up so System.err goes to a StringBuffer
<span class="fc" id="L95">      final StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L96">      System.setErr(new PrintStream(new OutputStream() {</span>
        @Override
        public void write(int b) throws IOException {
<span class="fc" id="L99">          sb.append((char)b);</span>
<span class="fc" id="L100">        }</span>
      }));
      
      // make call
<span class="fc" id="L104">      Exception e = new Exception();</span>
<span class="fc" id="L105">      ExceptionUtils.handleException(e);</span>
      
<span class="pc bpc" id="L107" title="1 of 2 branches missed.">      assertTrue(sb.length() &gt; 0);</span>
<span class="fc" id="L108">      assertTrue(sb.toString().contains(ExceptionUtils.stackToString(e)));</span>
    } finally {
<span class="fc" id="L110">      System.setErr(originalSystemErr);</span>
    }
<span class="fc" id="L112">  }</span>
  
  @Test
  @SuppressWarnings(&quot;resource&quot;)
  public void handleExceptionThrowExceptionTest() {
<span class="fc" id="L117">    final RuntimeException thrownException = new SuppressedStackRuntimeException();</span>
    // set handler that will throw exception
<span class="fc" id="L119">    ExceptionUtils.setThreadExceptionHandler(new ExceptionHandler() {</span>
      @Override
      public void handleException(Throwable thrown) {
<span class="fc" id="L122">        throw thrownException;</span>
      }
    });
    
<span class="fc" id="L126">    PrintStream originalSystemErr = System.err;</span>
    try {
      // set it up so System.err goes to a StringBuffer
<span class="fc" id="L129">      final StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L130">      System.setErr(new PrintStream(new OutputStream() {</span>
        @Override
        public void write(int b) throws IOException {
<span class="fc" id="L133">          sb.append((char)b);</span>
<span class="fc" id="L134">        }</span>
      }));
      
      // make call
<span class="fc" id="L138">      Exception e = new Exception();</span>
<span class="fc" id="L139">      ExceptionUtils.handleException(e);</span>
      
<span class="pc bpc" id="L141" title="1 of 2 branches missed.">      assertTrue(sb.length() &gt; 0);</span>
<span class="fc" id="L142">      String resultStr = sb.toString();</span>
<span class="fc" id="L143">      assertTrue(resultStr.contains(ExceptionUtils.stackToString(e)));</span>
<span class="fc" id="L144">      assertTrue(resultStr.contains(ExceptionUtils.stackToString(thrownException)));</span>
    } finally {
<span class="fc" id="L146">      System.setErr(originalSystemErr);</span>
    }
<span class="fc" id="L148">  }</span>
  
  @Test
  @SuppressWarnings(&quot;resource&quot;)
  public void handleExceptionWithThreadExceptionHandler() {
<span class="fc" id="L153">    PrintStream originalSystemErr = System.err;</span>
    try {
      // set it up so System.err goes to a StringBuffer
<span class="fc" id="L156">      final StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L157">      System.setErr(new PrintStream(new OutputStream() {</span>
        @Override
        public void write(int b) throws IOException {
<span class="nc" id="L160">          sb.append((char)b);</span>
<span class="nc" id="L161">        }</span>
      }));
      
<span class="fc" id="L164">      TestExceptionHandler teh = new TestExceptionHandler();</span>
<span class="fc" id="L165">      ExceptionUtils.setThreadExceptionHandler(teh);</span>
<span class="fc" id="L166">      TestExceptionHandler uncalledHandler = new TestExceptionHandler();</span>
<span class="fc" id="L167">      ExceptionUtils.setInheritableExceptionHandler(uncalledHandler);</span>
<span class="fc" id="L168">      ExceptionUtils.setDefaultExceptionHandler(uncalledHandler);</span>
      
      // make call
<span class="fc" id="L171">      Exception e = new Exception();</span>
<span class="fc" id="L172">      ExceptionUtils.handleException(e);</span>
        
<span class="fc" id="L174">      assertEquals(0, sb.length()); // should not have gone to std err</span>
<span class="fc" id="L175">      assertEquals(0, uncalledHandler.getCallCount());</span>
        
<span class="fc" id="L177">      assertEquals(1, teh.getCallCount());</span>
<span class="pc bpc" id="L178" title="1 of 2 branches missed.">      assertTrue(teh.getLastThrowable() == e);</span>
    } finally {
<span class="fc" id="L180">      System.setErr(originalSystemErr);</span>
    }
<span class="fc" id="L182">  }</span>
  
  @Test
  @SuppressWarnings(&quot;resource&quot;)
  public void handleExceptionWithInheritableThreadExceptionHandler() {
<span class="fc" id="L187">    PrintStream originalSystemErr = System.err;</span>
    try {
      // set it up so System.err goes to a StringBuffer
<span class="fc" id="L190">      final StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L191">      System.setErr(new PrintStream(new OutputStream() {</span>
        @Override
        public void write(int b) throws IOException {
<span class="nc" id="L194">          sb.append((char)b);</span>
<span class="nc" id="L195">        }</span>
      }));
      
<span class="fc" id="L198">      TestExceptionHandler teh = new TestExceptionHandler();</span>
<span class="fc" id="L199">      ExceptionUtils.setInheritableExceptionHandler(teh);</span>
<span class="fc" id="L200">      TestExceptionHandler uncalledHandler = new TestExceptionHandler();</span>
<span class="fc" id="L201">      ExceptionUtils.setDefaultExceptionHandler(uncalledHandler);</span>
      
      // make call
<span class="fc" id="L204">      Exception e = new Exception();</span>
<span class="fc" id="L205">      ExceptionUtils.handleException(e);</span>
        
<span class="fc" id="L207">      assertEquals(0, sb.length()); // should not have gone to std err</span>
<span class="fc" id="L208">      assertEquals(0, uncalledHandler.getCallCount());</span>
        
<span class="fc" id="L210">      assertEquals(1, teh.getCallCount());</span>
<span class="pc bpc" id="L211" title="1 of 2 branches missed.">      assertTrue(teh.getLastThrowable() == e);</span>
    } finally {
<span class="fc" id="L213">      System.setErr(originalSystemErr);</span>
    }
<span class="fc" id="L215">  }</span>
  
  @Test
  @SuppressWarnings(&quot;resource&quot;)
  public void handleExceptionWithDefaultThreadExceptionHandler() {
<span class="fc" id="L220">    PrintStream originalSystemErr = System.err;</span>
    try {
      // set it up so System.err goes to a StringBuffer
<span class="fc" id="L223">      final StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L224">      System.setErr(new PrintStream(new OutputStream() {</span>
        @Override
        public void write(int b) throws IOException {
<span class="nc" id="L227">          sb.append((char)b);</span>
<span class="nc" id="L228">        }</span>
      }));
      
<span class="fc" id="L231">      TestExceptionHandler teh = new TestExceptionHandler();</span>
<span class="fc" id="L232">      ExceptionUtils.setDefaultExceptionHandler(teh);</span>
      
      // make call
<span class="fc" id="L235">      Exception e = new Exception();</span>
<span class="fc" id="L236">      ExceptionUtils.handleException(e);</span>
        
<span class="fc" id="L238">      assertEquals(0, sb.length()); // should not have gone to std err</span>
        
<span class="fc" id="L240">      assertEquals(1, teh.getCallCount());</span>
<span class="pc bpc" id="L241" title="1 of 2 branches missed.">      assertTrue(teh.getLastThrowable() == e);</span>
    } finally {
<span class="fc" id="L243">      System.setErr(originalSystemErr);</span>
    }
<span class="fc" id="L245">  }</span>
  
  @Test
  @SuppressWarnings(&quot;resource&quot;)
  public void handleExceptionWithDefaultUncaughtExceptionHandler() {
<span class="fc" id="L250">    PrintStream originalSystemErr = System.err;</span>
    try {
      // set it up so System.err goes to a StringBuffer
<span class="fc" id="L253">      final StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L254">      System.setErr(new PrintStream(new OutputStream() {</span>
        @Override
        public void write(int b) throws IOException {
<span class="nc" id="L257">          sb.append((char)b);</span>
<span class="nc" id="L258">        }</span>
      }));
      
<span class="fc" id="L261">      TestUncaughtExceptionHandler ueh = new TestUncaughtExceptionHandler();</span>
<span class="fc" id="L262">      Thread.setDefaultUncaughtExceptionHandler(ueh);</span>
      
      // make call
<span class="fc" id="L265">      Exception e = new Exception();</span>
<span class="fc" id="L266">      ExceptionUtils.handleException(e);</span>
      
<span class="fc" id="L268">      assertEquals(0, sb.length()); // should not have gone to std err</span>
      
<span class="fc" id="L270">      assertEquals(1, ueh.getCallCount());</span>
<span class="pc bpc" id="L271" title="1 of 2 branches missed.">      assertTrue(ueh.getCalledWithThread() == Thread.currentThread());</span>
<span class="pc bpc" id="L272" title="1 of 2 branches missed.">      assertTrue(ueh.getCalledWithThrowable() == e);</span>
    } finally {
<span class="fc" id="L274">      System.setErr(originalSystemErr);</span>
    }
<span class="fc" id="L276">  }</span>
  
  @Test
  @SuppressWarnings(&quot;resource&quot;)
  public void handleExceptionWithUncaughtExceptionHandler() {
<span class="fc" id="L281">    PrintStream originalSystemErr = System.err;</span>
    try {
      // set it up so System.err goes to a StringBuffer
<span class="fc" id="L284">      final StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L285">      System.setErr(new PrintStream(new OutputStream() {</span>
        @Override
        public void write(int b) throws IOException {
<span class="nc" id="L288">          sb.append((char)b);</span>
<span class="nc" id="L289">        }</span>
      }));
      
<span class="fc" id="L292">      TestUncaughtExceptionHandler ueh = new TestUncaughtExceptionHandler();</span>
<span class="fc" id="L293">      Thread.currentThread().setUncaughtExceptionHandler(ueh);</span>
      
      // make call
<span class="fc" id="L296">      Exception e = new Exception();</span>
<span class="fc" id="L297">      ExceptionUtils.handleException(e);</span>
      
<span class="fc" id="L299">      assertEquals(0, sb.length()); // should not have gone to std err</span>
      
<span class="fc" id="L301">      assertEquals(1, ueh.getCallCount());</span>
<span class="pc bpc" id="L302" title="1 of 2 branches missed.">      assertTrue(ueh.getCalledWithThread() == Thread.currentThread());</span>
<span class="pc bpc" id="L303" title="1 of 2 branches missed.">      assertTrue(ueh.getCalledWithThrowable() == e);</span>
    } finally {
<span class="fc" id="L305">      System.setErr(originalSystemErr);</span>
    }
<span class="fc" id="L307">  }</span>
  
  @Test
  public void handleExceptionWithNullException() {
<span class="fc" id="L311">    TestExceptionHandler teh = new TestExceptionHandler();</span>
    
<span class="fc" id="L313">    ExceptionUtils.setDefaultExceptionHandler(teh);</span>
<span class="fc" id="L314">    ExceptionUtils.handleException(null);</span>
    
    // no exception should be thrown or called
<span class="fc" id="L317">    assertEquals(0, teh.getCallCount());</span>
<span class="fc" id="L318">  }</span>
  
  @Test (expected = IllegalArgumentException.class)
  public void getRootCauseFail() {
<span class="nc" id="L322">    ExceptionUtils.getRootCause(null);</span>
<span class="nc" id="L323">    fail(&quot;Exception should have thrown&quot;);</span>
<span class="nc" id="L324">  }</span>
  
  @Test
  public void getRootCauseNoCauseTest() {
<span class="fc" id="L328">    Exception e = new Exception();</span>
<span class="pc bpc" id="L329" title="1 of 2 branches missed.">    assertTrue(e == ExceptionUtils.getRootCause(e));</span>
<span class="fc" id="L330">  }</span>
  
  @Test
  public void getRootCauseTest() {
<span class="fc" id="L334">    Exception rootCause = new Exception();</span>
<span class="fc" id="L335">    Exception e1 = new Exception(rootCause);</span>
<span class="fc" id="L336">    Exception e2 = new Exception(e1);</span>
<span class="fc" id="L337">    Exception e3 = new Exception(e2);</span>
    
    
<span class="pc bpc" id="L340" title="1 of 2 branches missed.">    assertTrue(ExceptionUtils.getRootCause(e3) == rootCause);</span>
<span class="pc bpc" id="L341" title="1 of 2 branches missed.">    assertTrue(ExceptionUtils.getRootCause(e2) == rootCause);</span>
<span class="pc bpc" id="L342" title="1 of 2 branches missed.">    assertTrue(ExceptionUtils.getRootCause(e1) == rootCause);</span>
<span class="fc" id="L343">  }</span>
  
  @Test
  public void getRootCauseCycleTest() {
<span class="fc" id="L347">    Exception rootCause = new Exception();</span>
<span class="fc" id="L348">    Exception e1 = new Exception(rootCause);</span>
<span class="fc" id="L349">    Exception e2 = new Exception(e1);</span>
<span class="fc" id="L350">    rootCause.initCause(e2);</span>
    
<span class="pc bpc" id="L352" title="1 of 2 branches missed.">    assertTrue(ExceptionUtils.getRootCause(e2) == rootCause);</span>
<span class="fc" id="L353">  }</span>
  
  @Test
  public void getCauseOfTypeNoInputTest() {
<span class="fc" id="L357">    assertNull(ExceptionUtils.getCauseOfType(null, Exception.class));</span>
<span class="fc" id="L358">  }</span>
  
  @Test
  public void getCauseOfTypeMissingTest() {
<span class="fc" id="L362">    Exception e = new Exception(new SuppressedStackRuntimeException(new SuppressedStackRuntimeException()));</span>
<span class="fc" id="L363">    assertNull(ExceptionUtils.getCauseOfType(e, IllegalArgumentException.class));</span>
<span class="fc" id="L364">  }</span>
  
  @Test
  public void getCauseOfTypeTest() {
<span class="fc" id="L368">    IllegalArgumentException expected = new IllegalArgumentException(new Exception());</span>
<span class="fc" id="L369">    Exception e = new Exception(expected);</span>
<span class="pc bpc" id="L370" title="1 of 2 branches missed.">    assertTrue(expected == ExceptionUtils.getCauseOfType(e, IllegalArgumentException.class));</span>
<span class="fc" id="L371">  }</span>
  
  @Test
  public void getCauseOfTypeCycleTest() {
<span class="fc" id="L375">    IllegalArgumentException rootCause = new IllegalArgumentException();</span>
<span class="fc" id="L376">    Exception e1 = new Exception(rootCause);</span>
<span class="fc" id="L377">    Exception e2 = new Exception(e1);</span>
<span class="fc" id="L378">    rootCause.initCause(e2);</span>
    
<span class="fc" id="L380">    assertNull(ExceptionUtils.getCauseOfType(e2, UnsupportedOperationException.class));</span>
<span class="pc bpc" id="L381" title="1 of 2 branches missed.">    assertTrue(rootCause == ExceptionUtils.getCauseOfType(e2, IllegalArgumentException.class));</span>
<span class="fc" id="L382">  }</span>
  
  @Test
  public void hasCauseOfTypeNoInputTest() {
<span class="fc" id="L386">    assertFalse(ExceptionUtils.hasCauseOfType(null, Exception.class));</span>
<span class="fc" id="L387">  }</span>
  
  @Test
  public void hasCauseOfTypeMissingTest() {
<span class="fc" id="L391">    Exception e = new Exception(new SuppressedStackRuntimeException(new SuppressedStackRuntimeException()));</span>
<span class="fc" id="L392">    assertFalse(ExceptionUtils.hasCauseOfType(e, IllegalArgumentException.class));</span>
<span class="fc" id="L393">  }</span>
  
  @Test
  public void hasCauseOfTypeTest() {
<span class="fc" id="L397">    Exception e = new Exception(new IllegalArgumentException(new Exception()));</span>
<span class="fc" id="L398">    assertTrue(ExceptionUtils.hasCauseOfType(e, IllegalArgumentException.class));</span>
<span class="fc" id="L399">  }</span>
  
  @Test
  public void hasCauseOfTypeCycleTest() {
<span class="fc" id="L403">    IllegalArgumentException rootCause = new IllegalArgumentException();</span>
<span class="fc" id="L404">    Exception e1 = new Exception(rootCause);</span>
<span class="fc" id="L405">    Exception e2 = new Exception(e1);</span>
<span class="fc" id="L406">    rootCause.initCause(e2);</span>

<span class="fc" id="L408">    assertFalse(ExceptionUtils.hasCauseOfType(e2, UnsupportedOperationException.class));</span>
<span class="fc" id="L409">    assertTrue(ExceptionUtils.hasCauseOfType(e2, IllegalArgumentException.class));</span>
<span class="fc" id="L410">  }</span>
  
  @Test
  public void getCauseOfTypesNoInputTest() {
<span class="fc" id="L414">    assertNull(ExceptionUtils.getCauseOfTypes(null, Collections.singletonList(Exception.class)));</span>
<span class="fc" id="L415">  }</span>
  
  @Test
  public void getCauseOfTypesMissingTest() {
<span class="fc" id="L419">    Exception e = new Exception(new SuppressedStackRuntimeException(new SuppressedStackRuntimeException()));</span>
<span class="fc" id="L420">    assertNull(ExceptionUtils.getCauseOfTypes(e, Collections.singletonList(IllegalArgumentException.class)));</span>
<span class="fc" id="L421">  }</span>
  
  @Test
  public void getCauseOfTypesTest() {
<span class="fc" id="L425">    IllegalArgumentException expected = new IllegalArgumentException(new Exception());</span>
<span class="fc" id="L426">    Exception e = new Exception(expected);</span>
<span class="pc bpc" id="L427" title="1 of 2 branches missed.">    assertTrue(expected == ExceptionUtils.getCauseOfTypes(e, Collections.singletonList(IllegalArgumentException.class)));</span>
<span class="fc" id="L428">  }</span>
  
  @Test
  public void hasCauseOfTypesNoInputTest() {
<span class="fc" id="L432">    assertFalse(ExceptionUtils.hasCauseOfTypes(null, Collections.singletonList(Exception.class)));</span>
<span class="fc" id="L433">  }</span>
  
  @Test
  public void hasCauseOfTypesMissingTest() {
<span class="fc" id="L437">    Exception e = new Exception(new SuppressedStackRuntimeException(new SuppressedStackRuntimeException()));</span>
<span class="fc" id="L438">    assertFalse(ExceptionUtils.hasCauseOfTypes(e, Collections.singletonList(IllegalArgumentException.class)));</span>
<span class="fc" id="L439">  }</span>
  
  @Test
  public void hasCauseOfTypesTest() {
<span class="fc" id="L443">    Exception e = new Exception(new IllegalArgumentException(new Exception()));</span>
<span class="fc" id="L444">    assertTrue(ExceptionUtils.hasCauseOfTypes(e, Collections.singletonList(IllegalArgumentException.class)));</span>
<span class="fc" id="L445">  }</span>
  
  @Test
  public void makeRuntimeWithRuntimeTest() {
<span class="fc" id="L449">    RuntimeException testException = new SuppressedStackRuntimeException();</span>

<span class="fc" id="L451">    RuntimeException resultException = ExceptionUtils.makeRuntime(testException);</span>
<span class="fc" id="L452">    assertNotNull(resultException);</span>

    // we expect the exact same reference to come out
<span class="pc bpc" id="L455" title="1 of 2 branches missed.">    assertTrue(testException == resultException);</span>
<span class="fc" id="L456">  }</span>

  @Test
  public void makeRuntimeWithNonRuntimeTest() {
<span class="fc" id="L460">    Exception testException = new Exception();</span>

<span class="fc" id="L462">    RuntimeException resultException = ExceptionUtils.makeRuntime(testException);</span>
<span class="fc" id="L463">    assertNotNull(resultException);</span>
<span class="fc" id="L464">    assertTrue(resultException instanceof TransformedException);</span>

    // verify stack trace does not contain Util.makeRuntime inside it for when it created a new exception
<span class="fc" id="L467">    StackTraceElement[] stack = resultException.getStackTrace();</span>
<span class="fc bfc" id="L468" title="All 2 branches covered.">    for (StackTraceElement ste : stack) {</span>
<span class="fc" id="L469">      assertFalse(ste.getClassName().equals(ExceptionUtils.class.getName()));</span>
    }

    // verify the cause was our original exception
<span class="pc bpc" id="L473" title="1 of 2 branches missed.">    assertTrue(testException == resultException.getCause());</span>
<span class="fc" id="L474">  }</span>

  @Test
  public void makeRuntimeWithNullTest() {
<span class="fc" id="L478">    RuntimeException resultException = ExceptionUtils.makeRuntime(null);</span>
<span class="fc" id="L479">    assertNotNull(resultException);</span>

    // verify stack trace does not contain Util.makeRuntime inside it for when it created a new exception
<span class="fc" id="L482">    StackTraceElement[] stack = resultException.getStackTrace();</span>
<span class="fc bfc" id="L483" title="All 2 branches covered.">    for (StackTraceElement ste : stack) {</span>
<span class="fc" id="L484">      assertFalse(ste.getClass().getName().equals(ExceptionUtils.class.getName()));</span>
    }

    // verify that no cause is provided
<span class="fc" id="L488">    assertNull(resultException.getCause());</span>
<span class="fc" id="L489">  }</span>
  
  @Test
  public void makeRuntimeBooleanWithRuntimeTest() {
<span class="fc" id="L493">    RuntimeException testException = new SuppressedStackRuntimeException();</span>

<span class="fc" id="L495">    RuntimeException resultException = ExceptionUtils.makeRuntime(testException, false);</span>
<span class="fc" id="L496">    assertNotNull(resultException);</span>

    // we expect the exact same reference to come out
<span class="pc bpc" id="L499" title="1 of 2 branches missed.">    assertTrue(testException == resultException);</span>
<span class="fc" id="L500">  }</span>

  @Test
  public void makeRuntimeBooleanWithNonRuntimeTest() {
<span class="fc" id="L504">    Exception testException = new Exception();</span>

<span class="fc" id="L506">    RuntimeException resultException = ExceptionUtils.makeRuntime(testException, false);</span>
<span class="fc" id="L507">    assertNotNull(resultException);</span>
<span class="fc" id="L508">    assertTrue(resultException instanceof TransformedException);</span>

    // verify stack trace does not contain Util.makeRuntime inside it for when it created a new exception
<span class="fc" id="L511">    StackTraceElement[] stack = resultException.getStackTrace();</span>
<span class="fc bfc" id="L512" title="All 2 branches covered.">    for (StackTraceElement ste : stack) {</span>
<span class="fc" id="L513">      assertFalse(ste.getClassName().equals(ExceptionUtils.class.getName()));</span>
    }

    // verify the cause was our original exception
<span class="pc bpc" id="L517" title="1 of 2 branches missed.">    assertTrue(testException == resultException.getCause());</span>
<span class="fc" id="L518">  }</span>

  @Test
  public void makeRuntimeStackSuppressedWithNonRuntimeTest() {
<span class="fc" id="L522">    Exception testException = new Exception();</span>

<span class="fc" id="L524">    RuntimeException resultException = ExceptionUtils.makeRuntime(testException, true);</span>
<span class="fc" id="L525">    assertNotNull(resultException);</span>
<span class="fc" id="L526">    assertTrue(resultException instanceof TransformedSuppressedStackException);</span>

    // verify stack trace does not contain Util.makeRuntime inside it for when it created a new exception
<span class="fc" id="L529">    StackTraceElement[] stack = resultException.getStackTrace();</span>
<span class="fc bfc" id="L530" title="All 2 branches covered.">    for (StackTraceElement ste : stack) {</span>
<span class="fc" id="L531">      assertFalse(ste.getClassName().equals(ExceptionUtils.class.getName()));</span>
<span class="fc" id="L532">      assertFalse(ste.getClassName().equals(ExceptionUtilsTest.class.getName()));</span>
    }

    // verify the cause was our original exception
<span class="pc bpc" id="L536" title="1 of 2 branches missed.">    assertTrue(testException == resultException.getCause());</span>
<span class="fc" id="L537">  }</span>

  @Test
  public void makeRuntimeBooleanWithNullTest() {
<span class="fc" id="L541">    RuntimeException resultException = ExceptionUtils.makeRuntime(null, false);</span>
<span class="fc" id="L542">    assertNotNull(resultException);</span>

    // verify stack trace does not contain Util.makeRuntime inside it for when it created a new exception
<span class="fc" id="L545">    StackTraceElement[] stack = resultException.getStackTrace();</span>
<span class="fc bfc" id="L546" title="All 2 branches covered.">    for (StackTraceElement ste : stack) {</span>
<span class="fc" id="L547">      assertFalse(ste.getClass().getName().equals(ExceptionUtils.class.getName()));</span>
    }

    // verify that no cause is provided
<span class="fc" id="L551">    assertNull(resultException.getCause());</span>
<span class="fc" id="L552">  }</span>
  
  @Test
  public void stackToStringTest() {
<span class="fc" id="L556">    String message = &quot;TestMessage&quot;;</span>
<span class="fc" id="L557">    Exception testException = new Exception(message);</span>
<span class="fc" id="L558">    String result = ExceptionUtils.stackToString(testException);</span>
<span class="fc" id="L559">    assertNotNull(result);</span>
    
<span class="fc" id="L561">    StringTokenizer st = new StringTokenizer(result, &quot;\n&quot;);</span>
<span class="fc" id="L562">    assertEquals(testException.getStackTrace().length + 1, st.countTokens());</span>
<span class="fc" id="L563">    assertTrue(result.contains(message));</span>
<span class="fc" id="L564">  }</span>
  
  @Test
  public void stackToStringNullTest() {
<span class="fc" id="L568">    String result = ExceptionUtils.stackToString((Throwable)null);</span>
    
<span class="fc" id="L570">    assertNotNull(result);</span>
    
<span class="fc" id="L572">    assertEquals(0, result.length());</span>
<span class="fc" id="L573">  }</span>
  
  @Test
  public void writeStackToBuilderTest() {
<span class="fc" id="L577">    String message = &quot;TestMessage&quot;;</span>
<span class="fc" id="L578">    Exception testException = new Exception(message);</span>
<span class="fc" id="L579">    StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L580">    ExceptionUtils.writeStackTo(testException, sb);</span>
<span class="fc" id="L581">    String result = sb.toString();</span>
<span class="fc" id="L582">    assertNotNull(result);</span>
    
<span class="fc" id="L584">    StringTokenizer st = new StringTokenizer(result, &quot;\n&quot;);</span>
<span class="fc" id="L585">    assertEquals(testException.getStackTrace().length + 1, st.countTokens());</span>
<span class="fc" id="L586">    assertTrue(result.contains(message));</span>
<span class="fc" id="L587">  }</span>
  
  @Test
  public void writeStackToBuilderNullTest() {
<span class="fc" id="L591">    StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L592">    ExceptionUtils.writeStackTo((Throwable)null, sb);</span>
    
<span class="fc" id="L594">    assertEquals(0, sb.length());</span>
<span class="fc" id="L595">  }</span>
  
  @Test (expected = IllegalArgumentException.class)
  public void writeStackToBuilderFail() {
<span class="nc" id="L599">    ExceptionUtils.writeStackTo(new Exception(), (StringBuilder)null);</span>
<span class="nc" id="L600">  }</span>
  
  @Test
  public void writeStackToBufferTest() {
<span class="fc" id="L604">    String message = &quot;TestMessage&quot;;</span>
<span class="fc" id="L605">    Exception testException = new Exception(message);</span>
<span class="fc" id="L606">    StringBuffer sb = new StringBuffer();</span>
<span class="fc" id="L607">    ExceptionUtils.writeStackTo(testException, sb);</span>
<span class="fc" id="L608">    String result = sb.toString();</span>
<span class="fc" id="L609">    assertNotNull(result);</span>
    
<span class="fc" id="L611">    StringTokenizer st = new StringTokenizer(result, &quot;\n&quot;);</span>
<span class="fc" id="L612">    assertEquals(testException.getStackTrace().length + 1, st.countTokens());</span>
<span class="fc" id="L613">    assertTrue(result.contains(message));</span>
<span class="fc" id="L614">  }</span>
  
  @Test
  public void writeStackToBufferNullTest() {
<span class="fc" id="L618">    StringBuffer sb = new StringBuffer();</span>
<span class="fc" id="L619">    ExceptionUtils.writeStackTo(null, sb);</span>
    
<span class="fc" id="L621">    assertEquals(0, sb.length());</span>
<span class="fc" id="L622">  }</span>
  
  @Test (expected = IllegalArgumentException.class)
  public void writeStackToBufferFail() {
<span class="nc" id="L626">    ExceptionUtils.writeStackTo(new Exception(), (StringBuffer)null);</span>
<span class="nc" id="L627">  }</span>
  
  @Test
  public void stackToStringArrayTest() {
<span class="fc" id="L631">    Exception testException = new Exception();</span>
<span class="fc" id="L632">    String result = ExceptionUtils.stackToString(testException.getStackTrace());</span>
<span class="fc" id="L633">    assertNotNull(result);</span>
    
<span class="fc" id="L635">    StringTokenizer st = new StringTokenizer(result, &quot;\n&quot;);</span>
<span class="fc" id="L636">    assertEquals(testException.getStackTrace().length, st.countTokens());</span>
<span class="fc" id="L637">  }</span>
  
  @Test
  public void stackToStringArrayNullStackTest() {
<span class="fc" id="L641">    String result = ExceptionUtils.stackToString((StackTraceElement[])null);</span>
    
<span class="fc" id="L643">    assertNotNull(result);</span>
    
<span class="fc" id="L645">    assertEquals(0, result.length());</span>
<span class="fc" id="L646">  }</span>
  
  @Test
  public void writeArrayStackToBuilderTest() {
<span class="fc" id="L650">    Exception testException = new Exception();</span>
<span class="fc" id="L651">    StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L652">    ExceptionUtils.writeStackTo(testException.getStackTrace(), sb);</span>
<span class="fc" id="L653">    String result = sb.toString();</span>
<span class="fc" id="L654">    assertNotNull(result);</span>
    
<span class="fc" id="L656">    StringTokenizer st = new StringTokenizer(result, &quot;\n&quot;);</span>
<span class="fc" id="L657">    assertEquals(testException.getStackTrace().length, st.countTokens());</span>
<span class="fc" id="L658">  }</span>
  
  @Test
  public void writeArrayStackToBuilderNullTest() {
<span class="fc" id="L662">    StringBuilder sb = new StringBuilder();</span>
<span class="fc" id="L663">    ExceptionUtils.writeStackTo((StackTraceElement[])null, sb);</span>
    
<span class="fc" id="L665">    assertEquals(0, sb.length());</span>
<span class="fc" id="L666">  }</span>
  
  @Test (expected = IllegalArgumentException.class)
  public void writeArrayStackFail() {
<span class="nc" id="L670">    ExceptionUtils.writeStackTo(new Exception().getStackTrace(), null);</span>
<span class="nc" id="L671">  }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.1.201803210924</span></div></body></html>