<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>AbstractFutureCallbackFailureHandlerTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">threadly$All_in_threadly_test.exec</a> &gt; <a href="index.source.html" class="el_package">org.threadly.concurrent.future</a> &gt; <span class="el_source">AbstractFutureCallbackFailureHandlerTest.java</span></div><h1>AbstractFutureCallbackFailureHandlerTest.java</h1><pre class="source lang-java linenums">package org.threadly.concurrent.future;

import static org.junit.Assert.*;

import java.util.concurrent.atomic.AtomicReference;

import org.junit.Test;
import org.threadly.ThreadlyTester;

@SuppressWarnings(&quot;javadoc&quot;)
<span class="fc" id="L11">public class AbstractFutureCallbackFailureHandlerTest extends ThreadlyTester {</span>
  @Test
  public void resultIgnoredTest() {
<span class="fc" id="L14">    final AtomicReference&lt;Throwable&gt; failureProvided = new AtomicReference&lt;&gt;(null);</span>
<span class="fc" id="L15">    new AbstractFutureCallbackFailureHandler() {</span>
      @Override
      public void handleFailure(Throwable t) {
<span class="nc" id="L18">        failureProvided.set(t);</span>
<span class="nc" id="L19">      }</span>
<span class="fc" id="L20">    }.handleResult(new Exception());</span>
    // no exception should throw or other weird behavior
    
<span class="fc" id="L23">    assertNull(failureProvided.get());</span>
<span class="fc" id="L24">  }</span>
  
  @Test
  public void failureProvidedTest() {
<span class="fc" id="L28">    final Throwable testFailure = new Exception();</span>
<span class="fc" id="L29">    final AtomicReference&lt;Throwable&gt; failureProvided = new AtomicReference&lt;&gt;(null);</span>
<span class="fc" id="L30">    new AbstractFutureCallbackFailureHandler() {</span>
      @Override
      public void handleFailure(Throwable t) {
<span class="fc" id="L33">        failureProvided.set(t);</span>
<span class="fc" id="L34">      }</span>
<span class="fc" id="L35">    }.handleFailure(testFailure);</span>
    
<span class="pc bpc" id="L37" title="1 of 2 branches missed.">    assertTrue(testFailure == failureProvided.get());</span>
<span class="fc" id="L38">  }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.1.201803210924</span></div></body></html>